### ISSUE TITLE
armhf?

### ISSUE THREAD

**Issue by arogozhnikov** [yushulx/twain-wia-sane-scanner#1]
Hi, this project looks great, 

do you know if dynamsoft provides binaries for armhf (arm32) to run on raspbian?

**Comment by yushulx** [comment]
@arogozhnikov No more arm32 support as I know. But you can flash arm64 raspbian for Raspberry Pi.

**Comment by arogozhnikov** [comment]
> But you can flash arm64 raspbian for Raspberry Pi.

True. Except I am physically not in the same place as raspberry 😅  . Nevermind, thanks!
